### ISSUE TITLE
Org Access doesn't appear to be working

### ISSUE THREAD

**Issue by imaginIT** [cthonic-studios/verdaccio-github-auth#6]
I have GitHub-Auth configured with orgmode enabled and have setup access to use allow based on org but it doesn't appear to be working.  The user is in the organization but I get a forbidden when trying to access any of the packages in the registry.  When I switched access to be Team and added the user to the team things worked.

Here is essentially my config

```
auth:
  github-auth:
    org: orgName
    mode: token # token or basic. Token expects an auth token as the password. Basic is raw username/password for github. DEFAULT: token
    cachettl: 5 # OPTIONAL: How long to cache the user's teams in minutes. DEFAULT: 5
    orgmode: true # OPTIONAL: allow orgs to be placed in the `access` stanza.
packages:
  `@scope1/*`:
    access: org:orgName
   publish: "userWhoCanPublish"
   unpublish: "userWhoCanPublish"
```

Any insight on this issue would be greatly appreciated!

Thanks.
